#thymeleaf
spring:
    thymeleaf:
        cache: true
        encoding: UTF-8
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html

    messages:
        basename: i18n.login
